### ISSUE TITLE
Create "sign-in form" component

### ISSUE THREAD

**Issue by Stevemaster92** [team-bayou/UNO-Shareboard-WebApp#10]
Add a sign-in form (using email address and password) to login to the web app.

**Comment by parkersprouse** [comment]
I'll give this a shot. I feel like this is a fairly easy thing to do, and a good way to make some initial progress without immediately diving too deeply into it right off the bat.

**Comment by parkersprouse** [comment]
I'm gonna include the registration form in this. They're both part of the same feature and are both only used in one spot, so I'll make both forms at the same time.
